# Generated by Django 4.1 on 2022-09-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_description_alter_course_is_home_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='whatYouWillLearn',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
