# Generated by Django 4.1 on 2022-09-04 15:41

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0005_alter_course_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_images/%Y/%m/')),
                ('language', models.CharField(blank=True, max_length=30, null=True)),
                ('website', models.CharField(blank=True, max_length=75, null=True)),
                ('twitter', models.CharField(blank=True, max_length=75, null=True)),
                ('facebook', models.CharField(blank=True, max_length=75, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=75, null=True)),
                ('youtube', models.CharField(blank=True, max_length=75, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
