# Generated by Django 4.1 on 2022-09-09 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='profile_images/default_profile_image/user_default_profile_image.jpg', null=True, upload_to='profile_images/%Y/%m/'),
        ),
    ]
